(ns landing.agora.person.alias-words
  "The curated vocabulary a generated alias is drawn from — data only, no rule (see `alias`).

  One entry per language, holding everything that language needs so the drawing rule branches on a
  **field of the data**, never on the language:

    :order       the two slots in reading order — French says « Prémisse Cuivrée » (noun first),
                 English says \"Coppered Premise\" (adjective first)
    :adjectives  `[\"cuivré\" \"cuivrée\"]` — masculine then feminine; a language that does not
                 inflect gives the single form it has
    :nouns       `[\"prémisse\" :f]` — the word and the gender that selects the adjective's form; a
                 language without gender omits it and takes the first form

  The lexical field is the forge and the agora — reasoning, metal, fire, tools, measure — so an alias
  reads as belonging here. Every word is chosen to be neutral: nothing that carries a judgment, a
  nationality, a real person or a connotation someone could be stuck with in public.

  The number of aliases is the product of the two lists (`alias/alias-count`), so widening the
  vocabulary is a change to this file alone."
  (:refer-clojure :exclude [words]))

(def words
  {:fr {:order [:noun :adjective]
        :adjectives [["cuivré" "cuivrée"]
                     ["doré" "dorée"]
                     ["argenté" "argentée"]
                     ["bronzé" "bronzée"]
                     ["vermeil" "vermeille"]
                     ["patiné" "patinée"]
                     ["bruni" "brunie"]
                     ["poli" "polie"]
                     ["martelé" "martelée"]
                     ["forgé" "forgée"]
                     ["trempé" "trempée"]
                     ["fondu" "fondue"]
                     ["coulé" "coulée"]
                     ["laminé" "laminée"]
                     ["ciselé" "ciselée"]
                     ["gravé" "gravée"]
                     ["buriné" "burinée"]
                     ["riveté" "rivetée"]
                     ["soudé" "soudée"]
                     ["recuit" "recuite"]
                     ["étamé" "étamée"]
                     ["damassé" "damassée"]
                     ["émaillé" "émaillée"]
                     ["serti" "sertie"]
                     ["ardent" "ardente"]
                     ["brûlant" "brûlante"]
                     ["incandescent" "incandescente"]
                     ["rougeoyant" "rougeoyante"]
                     ["flamboyant" "flamboyante"]
                     ["fumant" "fumante"]
                     ["braisé" "braisée"]
                     ["attisé" "attisée"]
                     ["embrasé" "embrasée"]
                     ["tiède" "tiède"]
                     ["refroidi" "refroidie"]
                     ["givré" "givrée"]
                     ["lumineux" "lumineuse"]
                     ["clair" "claire"]
                     ["éclatant" "éclatante"]
                     ["brillant" "brillante"]
                     ["luisant" "luisante"]
                     ["scintillant" "scintillante"]
                     ["mat" "mate"]
                     ["sombre" "sombre"]
                     ["voilé" "voilée"]
                     ["diaphane" "diaphane"]
                     ["limpide" "limpide"]
                     ["opalin" "opaline"]
                     ["nacré" "nacrée"]
                     ["irisé" "irisée"]
                     ["chatoyant" "chatoyante"]
                     ["translucide" "translucide"]
                     ["cristallin" "cristalline"]
                     ["aurorial" "auroriale"]
                     ["aiguisé" "aiguisée"]
                     ["affûté" "affûtée"]
                     ["tranchant" "tranchante"]
                     ["acéré" "acérée"]
                     ["dentelé" "dentelée"]
                     ["effilé" "effilée"]
                     ["robuste" "robuste"]
                     ["massif" "massive"]
                     ["dense" "dense"]
                     ["compact" "compacte"]
                     ["souple" "souple"]
                     ["ductile" "ductile"]
                     ["malléable" "malléable"]
                     ["tenace" "tenace"]
                     ["résistant" "résistante"]
                     ["élastique" "élastique"]
                     ["léger" "légère"]
                     ["fin" "fine"]
                     ["ample" "ample"]
                     ["vaste" "vaste"]
                     ["profond" "profonde"]
                     ["rigoureux" "rigoureuse"]
                     ["sobre" "sobre"]
                     ["franc" "franche"]
                     ["net" "nette"]
                     ["subtil" "subtile"]
                     ["patient" "patiente"]
                     ["obstiné" "obstinée"]
                     ["opiniâtre" "opiniâtre"]
                     ["prudent" "prudente"]
                     ["hardi" "hardie"]
                     ["serein" "sereine"]
                     ["lucide" "lucide"]
                     ["austère" "austère"]
                     ["précis" "précise"]
                     ["exact" "exacte"]
                     ["sagace" "sagace"]
                     ["avisé" "avisée"]
                     ["méthodique" "méthodique"]
                     ["minutieux" "minutieuse"]
                     ["scrupuleux" "scrupuleuse"]
                     ["docte" "docte"]
                     ["éclairé" "éclairée"]
                     ["curieux" "curieuse"]
                     ["songeur" "songeuse"]
                     ["pensif" "pensive"]
                     ["discret" "discrète"]
                     ["silencieux" "silencieuse"]
                     ["attentif" "attentive"]
                     ["vigilant" "vigilante"]
                     ["posé" "posée"]
                     ["mesuré" "mesurée"]
                     ["constant" "constante"]
                     ["fidèle" "fidèle"]
                     ["loyal" "loyale"]
                     ["probe" "probe"]
                     ["intègre" "intègre"]
                     ["modeste" "modeste"]
                     ["affable" "affable"]
                     ["courtois" "courtoise"]
                     ["droit" "droite"]
                     ["oblique" "oblique"]
                     ["courbe" "courbe"]
                     ["anguleux" "anguleuse"]
                     ["carré" "carrée"]
                     ["rond" "ronde"]
                     ["élancé" "élancée"]
                     ["trapu" "trapue"]
                     ["svelte" "svelte"]
                     ["écarlate" "écarlate"]
                     ["pourpre" "pourpre"]
                     ["safran" "safran"]
                     ["ocre" "ocre"]
                     ["ambré" "ambrée"]
                     ["fauve" "fauve"]
                     ["bistre" "bistre"]
                     ["indigo" "indigo"]
                     ["azuré" "azurée"]
                     ["céruléen" "céruléenne"]
                     ["olivâtre" "olivâtre"]
                     ["cendré" "cendrée"]
                     ["ivoirin" "ivoirine"]
                     ["charbonneux" "charbonneuse"]
                     ["rouillé" "rouillée"]
                     ["oxydé" "oxydée"]
                     ["ferreux" "ferreuse"]
                     ["plombé" "plombée"]
                     ["zingué" "zinguée"]
                     ["nickelé" "nickelée"]
                     ["chromé" "chromée"]
                     ["laitonné" "laitonnée"]
                     ["platiné" "platinée"]
                     ["aurifère" "aurifère"]
                     ["matinal" "matinale"]
                     ["vespéral" "vespérale"]
                     ["nocturne" "nocturne"]
                     ["hivernal" "hivernale"]
                     ["estival" "estivale"]
                     ["automnal" "automnale"]
                     ["printanier" "printanière"]
                     ["boréal" "boréale"]
                     ["austral" "australe"]
                     ["polaire" "polaire"]
                     ["insulaire" "insulaire"]
                     ["montagnard" "montagnarde"]
                     ["marin" "marine"]
                     ["fluvial" "fluviale"]
                     ["sylvestre" "sylvestre"]
                     ["minéral" "minérale"]
                     ["granitique" "granitique"]
                     ["calcaire" "calcaire"]
                     ["basaltique" "basaltique"]
                     ["schisteux" "schisteuse"]
                     ["sableux" "sableuse"]
                     ["argileux" "argileuse"]
                     ["salin" "saline"]
                     ["sulfureux" "sulfureuse"]
                     ["volcanique" "volcanique"]
                     ["sismique" "sismique"]
                     ["tellurique" "tellurique"]
                     ["orageux" "orageuse"]
                     ["venteux" "venteuse"]
                     ["brumeux" "brumeuse"]
                     ["pluvieux" "pluvieuse"]
                     ["neigeux" "neigeuse"]
                     ["glacé" "glacée"]
                     ["torride" "torride"]
                     ["aride" "aride"]
                     ["humide" "humide"]
                     ["sec" "sèche"]
                     ["fertile" "fertile"]
                     ["verdoyant" "verdoyante"]
                     ["premier" "première"]
                     ["second" "seconde"]
                     ["ultime" "ultime"]
                     ["central" "centrale"]
                     ["liminaire" "liminaire"]
                     ["cardinal" "cardinale"]
                     ["majeur" "majeure"]
                     ["mineur" "mineure"]
                     ["double" "double"]
                     ["triple" "triple"]
                     ["unique" "unique"]
                     ["commun" "commune"]
                     ["singulier" "singulière"]
                     ["voisin" "voisine"]
                     ["lointain" "lointaine"]
                     ["ancien" "ancienne"]
                     ["antique" "antique"]
                     ["récent" "récente"]
                     ["durable" "durable"]
                     ["éphémère" "éphémère"]
                     ["perpétuel" "perpétuelle"]
                     ["matutinal" "matutinale"]
                     ["tardif" "tardive"]
                     ["hâtif" "hâtive"]
                     ["lent" "lente"]
                     ["vif" "vive"]
                     ["prompt" "prompte"]
                     ["mobile" "mobile"]
                     ["immobile" "immobile"]
                     ["errant" "errante"]
                     ["nomade" "nomade"]
                     ["sédentaire" "sédentaire"]
                     ["itinérant" "itinérante"]
                     ["ouvert" "ouverte"]
                     ["clos" "close"]
                     ["scellé" "scellée"]
                     ["ouvragé" "ouvragée"]
                     ["sculpté" "sculptée"]
                     ["tissé" "tissée"]
                     ["tressé" "tressée"]
                     ["noué" "nouée"]
                     ["plié" "pliée"]
                     ["déployé" "déployée"]
                     ["assemblé" "assemblée"]
                     ["ajusté" "ajustée"]
                     ["aligné" "alignée"]
                     ["gradué" "graduée"]
                     ["calibré" "calibrée"]
                     ["étalonné" "étalonnée"]
                     ["numéroté" "numérotée"]
                     ["chiffré" "chiffrée"]
                     ["annoté" "annotée"]
                     ["paginé" "paginée"]
                     ["relié" "reliée"]
                     ["enluminé" "enluminée"]
                     ["manuscrit" "manuscrite"]
                     ["imprimé" "imprimée"]
                     ["estampé" "estampée"]
                     ["frappé" "frappée"]
                     ["poinçonné" "poinçonnée"]
                     ["signé" "signée"]
                     ["daté" "datée"]
                     ["attesté" "attestée"]
                     ["avéré" "avérée"]
                     ["établi" "établie"]
                     ["fondé" "fondée"]
                     ["étayé" "étayée"]
                     ["démontré" "démontrée"]
                     ["vérifié" "vérifiée"]
                     ["éprouvé" "éprouvée"]
                     ["contesté" "contestée"]
                     ["disputé" "disputée"]
                     ["débattu" "débattue"]
                     ["nuancé" "nuancée"]
                     ["tempéré" "tempérée"]
                     ["pondéré" "pondérée"]
                     ["équilibré" "équilibrée"]
                     ["symétrique" "symétrique"]
                     ["concentrique" "concentrique"]
                     ["parallèle" "parallèle"]
                     ["perpendiculaire" "perpendiculaire"]
                     ["tangent" "tangente"]
                     ["radial" "radiale"]
                     ["spiralé" "spiralée"]
                     ["hélicoïdal" "hélicoïdale"]]
        :nouns [["prémisse" :f]
                ["argument" :m]
                ["corollaire" :m]
                ["axiome" :m]
                ["lemme" :m]
                ["thèse" :f]
                ["antithèse" :f]
                ["synthèse" :f]
                ["postulat" :m]
                ["inférence" :f]
                ["déduction" :f]
                ["induction" :f]
                ["preuve" :f]
                ["conjecture" :f]
                ["hypothèse" :f]
                ["objection" :f]
                ["réfutation" :f]
                ["démonstration" :f]
                ["théorème" :m]
                ["proposition" :f]
                ["assertion" :f]
                ["énoncé" :m]
                ["principe" :m]
                ["fondement" :m]
                ["socle" :m]
                ["pivot" :m]
                ["maxime" :f]
                ["adage" :m]
                ["sentence" :f]
                ["aphorisme" :m]
                ["doute" :m]
                ["certitude" :f]
                ["nuance" :f]
                ["rigueur" :f]
                ["clarté" :f]
                ["méthode" :f]
                ["analyse" :f]
                ["critique" :f]
                ["examen" :m]
                ["épreuve" :f]
                ["question" :f]
                ["réponse" :f]
                ["débat" :m]
                ["dialogue" :m]
                ["discours" :m]
                ["plaidoyer" :m]
                ["traité" :m]
                ["essai" :m]
                ["glose" :f]
                ["note" :f]
                ["renvoi" :m]
                ["citation" :f]
                ["extrait" :m]
                ["passage" :m]
                ["chapitre" :m]
                ["page" :f]
                ["ligne" :f]
                ["terme" :m]
                ["lexique" :m]
                ["glossaire" :m]
                ["définition" :f]
                ["portée" :f]
                ["contour" :m]
                ["limite" :f]
                ["seuil" :m]
                ["degré" :m]
                ["palier" :m]
                ["échelle" :f]
                ["mesure" :f]
                ["balance" :f]
                ["équerre" :f]
                ["compas" :m]
                ["règle" :f]
                ["niveau" :m]
                ["gabarit" :m]
                ["cadran" :m]
                ["sablier" :m]
                ["boussole" :f]
                ["sextant" :m]
                ["astrolabe" :m]
                ["gnomon" :m]
                ["enclume" :f]
                ["braise" :f]
                ["forge" :f]
                ["creuset" :m]
                ["fourneau" :m]
                ["soufflet" :m]
                ["marteau" :m]
                ["masse" :f]
                ["étau" :m]
                ["lime" :f]
                ["burin" :m]
                ["ciseau" :m]
                ["pince" :f]
                ["tenaille" :f]
                ["meule" :f]
                ["fonte" :f]
                ["alliage" :m]
                ["trempe" :f]
                ["lingot" :m]
                ["barre" :f]
                ["tige" :f]
                ["plaque" :f]
                ["feuille" :f]
                ["copeau" :m]
                ["étincelle" :f]
                ["flamme" :f]
                ["brasier" :m]
                ["cendre" :f]
                ["charbon" :m]
                ["scorie" :f]
                ["minerai" :m]
                ["veine" :f]
                ["filon" :m]
                ["gangue" :f]
                ["quartz" :m]
                ["cuivre" :m]
                ["bronze" :m]
                ["laiton" :m]
                ["acier" :m]
                ["étain" :m]
                ["zinc" :m]
                ["platine" :m]
                ["cristal" :m]
                ["gemme" :f]
                ["agate" :f]
                ["onyx" :m]
                ["jaspe" :m]
                ["silex" :m]
                ["granit" :m]
                ["marbre" :m]
                ["ardoise" :f]
                ["argile" :f]
                ["grès" :m]
                ["basalte" :m]
                ["obsidienne" :f]
                ["améthyste" :f]
                ["topaze" :f]
                ["opale" :f]
                ["moule" :m]
                ["matrice" :f]
                ["empreinte" :f]
                ["sceau" :m]
                ["coin" :m]
                ["poinçon" :m]
                ["estampe" :f]
                ["gravure" :f]
                ["taille" :f]
                ["facette" :f]
                ["arête" :f]
                ["angle" :m]
                ["courbe" :f]
                ["spirale" :f]
                ["cercle" :m]
                ["carré" :m]
                ["triangle" :m]
                ["prisme" :m]
                ["sphère" :f]
                ["cube" :m]
                ["agora" :f]
                ["colonne" :f]
                ["portique" :m]
                ["fronton" :m]
                ["stèle" :f]
                ["tribune" :f]
                ["parvis" :m]
                ["atelier" :m]
                ["chantier" :m]
                ["échafaud" :m]
                ["arche" :f]
                ["voûte" :f]
                ["pilier" :m]
                ["poutre" :f]
                ["linteau" :m]
                ["clé" :f]
                ["serrure" :f]
                ["verrou" :m]
                ["charnière" :f]
                ["gond" :m]
                ["pont" :m]
                ["gué" :m]
                ["sentier" :m]
                ["chemin" :m]
                ["sillon" :m]
                ["trace" :f]
                ["piste" :f]
                ["détour" :m]
                ["carrefour" :m]
                ["borne" :f]
                ["repère" :m]
                ["jalon" :m]
                ["fil" :m]
                ["trame" :f]
                ["chaîne" :f]
                ["nœud" :m]
                ["maille" :f]
                ["corde" :f]
                ["tresse" :f]
                ["câble" :m]
                ["aurore" :f]
                ["crépuscule" :m]
                ["zénith" :m]
                ["orient" :m]
                ["levant" :m]
                ["couchant" :m]
                ["midi" :m]
                ["minuit" :m]
                ["solstice" :m]
                ["équinoxe" :m]
                ["marée" :f]
                ["courant" :m]
                ["source" :f]
                ["affluent" :m]
                ["estuaire" :m]
                ["delta" :m]
                ["cascade" :f]
                ["torrent" :m]
                ["ruisseau" :m]
                ["étang" :m]
                ["colline" :f]
                ["crête" :f]
                ["vallon" :m]
                ["plateau" :m]
                ["falaise" :f]
                ["grotte" :f]
                ["caverne" :f]
                ["abîme" :m]
                ["clairière" :f]
                ["futaie" :f]
                ["bosquet" :m]
                ["haie" :f]
                ["racine" :f]
                ["rameau" :m]
                ["bourgeon" :m]
                ["écorce" :f]
                ["graine" :f]
                ["germe" :m]
                ["sève" :f]
                ["résine" :f]
                ["lanterne" :f]
                ["fanal" :m]
                ["phare" :m]
                ["flambeau" :m]
                ["chandelle" :f]
                ["mèche" :f]
                ["lampe" :f]
                ["veilleuse" :f]
                ["miroir" :m]
                ["lentille" :f]
                ["loupe" :f]
                ["lunette" :f]
                ["reflet" :m]
                ["ombre" :f]
                ["halo" :m]
                ["lueur" :f]
                ["écho" :m]
                ["murmure" :m]
                ["cadence" :f]
                ["tempo" :m]
                ["refrain" :m]
                ["silence" :m]
                ["pause" :f]
                ["accord" :m]]}
   :en {:order [:adjective :noun]
        :adjectives [["coppered"]
                     ["gilded"]
                     ["silvered"]
                     ["bronzed"]
                     ["vermilion"]
                     ["patinated"]
                     ["burnished"]
                     ["polished"]
                     ["hammered"]
                     ["forged"]
                     ["tempered"]
                     ["molten"]
                     ["cast"]
                     ["rolled"]
                     ["chiselled"]
                     ["engraved"]
                     ["etched"]
                     ["riveted"]
                     ["welded"]
                     ["annealed"]
                     ["tinned"]
                     ["damascened"]
                     ["enamelled"]
                     ["inset"]
                     ["ardent"]
                     ["burning"]
                     ["incandescent"]
                     ["glowing"]
                     ["flaming"]
                     ["smoking"]
                     ["kindled"]
                     ["stoked"]
                     ["ablaze"]
                     ["lukewarm"]
                     ["cooled"]
                     ["frosted"]
                     ["luminous"]
                     ["clear"]
                     ["radiant"]
                     ["brilliant"]
                     ["gleaming"]
                     ["glittering"]
                     ["matte"]
                     ["dusky"]
                     ["veiled"]
                     ["diaphanous"]
                     ["limpid"]
                     ["opaline"]
                     ["pearled"]
                     ["iridescent"]
                     ["shimmering"]
                     ["translucent"]
                     ["crystalline"]
                     ["auroral"]
                     ["sharpened"]
                     ["honed"]
                     ["cutting"]
                     ["keen"]
                     ["serrated"]
                     ["tapered"]
                     ["sturdy"]
                     ["massive"]
                     ["dense"]
                     ["compact"]
                     ["supple"]
                     ["ductile"]
                     ["malleable"]
                     ["tenacious"]
                     ["resilient"]
                     ["elastic"]
                     ["light"]
                     ["fine"]
                     ["ample"]
                     ["vast"]
                     ["deep"]
                     ["rigorous"]
                     ["sober"]
                     ["frank"]
                     ["crisp"]
                     ["subtle"]
                     ["patient"]
                     ["dogged"]
                     ["steadfast"]
                     ["prudent"]
                     ["bold"]
                     ["serene"]
                     ["lucid"]
                     ["austere"]
                     ["precise"]
                     ["exact"]
                     ["sagacious"]
                     ["shrewd"]
                     ["methodical"]
                     ["meticulous"]
                     ["scrupulous"]
                     ["learned"]
                     ["enlightened"]
                     ["curious"]
                     ["musing"]
                     ["pensive"]
                     ["discreet"]
                     ["silent"]
                     ["attentive"]
                     ["vigilant"]
                     ["poised"]
                     ["measured"]
                     ["constant"]
                     ["faithful"]
                     ["loyal"]
                     ["upright"]
                     ["candid"]
                     ["modest"]
                     ["affable"]
                     ["courteous"]
                     ["straight"]
                     ["oblique"]
                     ["curved"]
                     ["angular"]
                     ["squared"]
                     ["rounded"]
                     ["slender"]
                     ["stocky"]
                     ["svelte"]
                     ["scarlet"]
                     ["purple"]
                     ["saffron"]
                     ["ochre"]
                     ["amber"]
                     ["tawny"]
                     ["bistre"]
                     ["indigo"]
                     ["azure"]
                     ["cerulean"]
                     ["olive"]
                     ["ashen"]
                     ["ivory"]
                     ["charcoal"]
                     ["rusted"]
                     ["oxidised"]
                     ["ferrous"]
                     ["leaden"]
                     ["galvanised"]
                     ["nickelled"]
                     ["chromed"]
                     ["brazen"]
                     ["platinum"]
                     ["auriferous"]
                     ["morning"]
                     ["vesperal"]
                     ["nocturnal"]
                     ["wintry"]
                     ["estival"]
                     ["autumnal"]
                     ["vernal"]
                     ["boreal"]
                     ["austral"]
                     ["polar"]
                     ["insular"]
                     ["highland"]
                     ["marine"]
                     ["fluvial"]
                     ["sylvan"]
                     ["mineral"]
                     ["granitic"]
                     ["calcareous"]
                     ["basaltic"]
                     ["schistose"]
                     ["sandy"]
                     ["clayey"]
                     ["saline"]
                     ["sulphurous"]
                     ["volcanic"]
                     ["seismic"]
                     ["telluric"]
                     ["stormy"]
                     ["windswept"]
                     ["misty"]
                     ["rainy"]
                     ["snowy"]
                     ["glacial"]
                     ["torrid"]
                     ["arid"]
                     ["humid"]
                     ["dry"]
                     ["fertile"]
                     ["verdant"]
                     ["first"]
                     ["second"]
                     ["ultimate"]
                     ["central"]
                     ["liminal"]
                     ["cardinal"]
                     ["major"]
                     ["minor"]
                     ["double"]
                     ["triple"]
                     ["singular"]
                     ["common"]
                     ["neighbouring"]
                     ["distant"]
                     ["ancient"]
                     ["antique"]
                     ["recent"]
                     ["lasting"]
                     ["ephemeral"]
                     ["perpetual"]
                     ["matutinal"]
                     ["belated"]
                     ["hasty"]
                     ["slow"]
                     ["quick"]
                     ["prompt"]
                     ["mobile"]
                     ["still"]
                     ["wandering"]
                     ["nomadic"]
                     ["settled"]
                     ["itinerant"]
                     ["open"]
                     ["closed"]
                     ["sealed"]
                     ["wrought"]
                     ["sculpted"]
                     ["woven"]
                     ["braided"]
                     ["knotted"]
                     ["folded"]
                     ["unfurled"]
                     ["assembled"]
                     ["fitted"]
                     ["aligned"]
                     ["graduated"]
                     ["calibrated"]
                     ["gauged"]
                     ["numbered"]
                     ["ciphered"]
                     ["annotated"]
                     ["paginated"]
                     ["bound"]
                     ["illuminated"]
                     ["handwritten"]
                     ["printed"]
                     ["stamped"]
                     ["struck"]
                     ["punched"]
                     ["signed"]
                     ["dated"]
                     ["attested"]
                     ["proven"]
                     ["established"]
                     ["founded"]
                     ["buttressed"]
                     ["demonstrated"]
                     ["verified"]
                     ["tried"]
                     ["contested"]
                     ["disputed"]
                     ["debated"]
                     ["nuanced"]
                     ["temperate"]
                     ["weighted"]
                     ["balanced"]
                     ["symmetric"]
                     ["concentric"]
                     ["parallel"]
                     ["perpendicular"]
                     ["tangent"]
                     ["radial"]
                     ["spiralled"]
                     ["helical"]]
        :nouns [["premise"]
                ["argument"]
                ["corollary"]
                ["axiom"]
                ["lemma"]
                ["thesis"]
                ["antithesis"]
                ["synthesis"]
                ["postulate"]
                ["inference"]
                ["deduction"]
                ["induction"]
                ["proof"]
                ["conjecture"]
                ["hypothesis"]
                ["objection"]
                ["rebuttal"]
                ["demonstration"]
                ["theorem"]
                ["proposition"]
                ["assertion"]
                ["statement"]
                ["principle"]
                ["grounding"]
                ["bedrock"]
                ["pivot"]
                ["maxim"]
                ["adage"]
                ["sentence"]
                ["aphorism"]
                ["doubt"]
                ["certainty"]
                ["nuance"]
                ["rigour"]
                ["clarity"]
                ["method"]
                ["analysis"]
                ["critique"]
                ["scrutiny"]
                ["ordeal"]
                ["question"]
                ["answer"]
                ["debate"]
                ["dialogue"]
                ["discourse"]
                ["plea"]
                ["treatise"]
                ["essay"]
                ["gloss"]
                ["note"]
                ["reference"]
                ["citation"]
                ["extract"]
                ["passage"]
                ["chapter"]
                ["page"]
                ["line"]
                ["term"]
                ["lexicon"]
                ["glossary"]
                ["definition"]
                ["scope"]
                ["outline"]
                ["limit"]
                ["threshold"]
                ["degree"]
                ["landing"]
                ["scale"]
                ["measure"]
                ["balance"]
                ["square"]
                ["compass"]
                ["rule"]
                ["level"]
                ["template"]
                ["dial"]
                ["hourglass"]
                ["lodestone"]
                ["sextant"]
                ["astrolabe"]
                ["gnomon"]
                ["anvil"]
                ["ember"]
                ["forge"]
                ["crucible"]
                ["furnace"]
                ["bellows"]
                ["hammer"]
                ["sledge"]
                ["vise"]
                ["file"]
                ["burin"]
                ["chisel"]
                ["pliers"]
                ["tongs"]
                ["grindstone"]
                ["castiron"]
                ["alloy"]
                ["quench"]
                ["ingot"]
                ["bar"]
                ["rod"]
                ["plate"]
                ["sheet"]
                ["shaving"]
                ["spark"]
                ["flame"]
                ["blaze"]
                ["ash"]
                ["coal"]
                ["slag"]
                ["ore"]
                ["vein"]
                ["lode"]
                ["gangue"]
                ["quartz"]
                ["copper"]
                ["bronze"]
                ["brass"]
                ["steel"]
                ["tin"]
                ["zinc"]
                ["platinum"]
                ["crystal"]
                ["gem"]
                ["agate"]
                ["onyx"]
                ["jasper"]
                ["flint"]
                ["granite"]
                ["marble"]
                ["slate"]
                ["clay"]
                ["sandstone"]
                ["basalt"]
                ["obsidian"]
                ["amethyst"]
                ["topaz"]
                ["opal"]
                ["mould"]
                ["matrix"]
                ["imprint"]
                ["seal"]
                ["wedge"]
                ["punch"]
                ["stamp"]
                ["engraving"]
                ["cut"]
                ["facet"]
                ["edge"]
                ["angle"]
                ["curve"]
                ["spiral"]
                ["circle"]
                ["quadrant"]
                ["triangle"]
                ["prism"]
                ["sphere"]
                ["cube"]
                ["agora"]
                ["column"]
                ["portico"]
                ["pediment"]
                ["stele"]
                ["rostrum"]
                ["forecourt"]
                ["workshop"]
                ["worksite"]
                ["scaffold"]
                ["arch"]
                ["vault"]
                ["pillar"]
                ["beam"]
                ["lintel"]
                ["key"]
                ["lock"]
                ["bolt"]
                ["hinge"]
                ["pintle"]
                ["bridge"]
                ["ford"]
                ["path"]
                ["road"]
                ["furrow"]
                ["trace"]
                ["trail"]
                ["detour"]
                ["crossroads"]
                ["milestone"]
                ["marker"]
                ["waypoint"]
                ["thread"]
                ["weft"]
                ["chain"]
                ["knot"]
                ["mesh"]
                ["cord"]
                ["braid"]
                ["cable"]
                ["dawn"]
                ["dusk"]
                ["zenith"]
                ["orient"]
                ["sunrise"]
                ["sunset"]
                ["noon"]
                ["midnight"]
                ["solstice"]
                ["equinox"]
                ["tide"]
                ["current"]
                ["spring"]
                ["tributary"]
                ["estuary"]
                ["delta"]
                ["cascade"]
                ["torrent"]
                ["brook"]
                ["pond"]
                ["hill"]
                ["ridge"]
                ["dale"]
                ["plateau"]
                ["cliff"]
                ["grotto"]
                ["cavern"]
                ["abyss"]
                ["glade"]
                ["grove"]
                ["thicket"]
                ["hedge"]
                ["root"]
                ["bough"]
                ["bud"]
                ["bark"]
                ["seed"]
                ["germ"]
                ["sap"]
                ["resin"]
                ["lantern"]
                ["beacon"]
                ["lighthouse"]
                ["torch"]
                ["candle"]
                ["wick"]
                ["lamp"]
                ["nightlight"]
                ["mirror"]
                ["lens"]
                ["loupe"]
                ["eyeglass"]
                ["reflection"]
                ["shadow"]
                ["glimmer"]
                ["gleam"]
                ["echo"]
                ["murmur"]
                ["cadence"]
                ["metre"]
                ["refrain"]
                ["silence"]
                ["pause"]
                ["chord"]]}})
