-- Agora — MVP schema (rollback). Drops every Agora table.
DROP TABLE IF EXISTS `AGORA_SUCCESSOR`;
DROP TABLE IF EXISTS `AGORA_ARTICLE`;
DROP TABLE IF EXISTS `AGORA_NODE`;
DROP TABLE IF EXISTS `AGORA_USER`;
