-- Agora / Logos — MVP schema (rollback). Drops every Agora table.
DROP TABLE IF EXISTS `AGORA_KI_EDGE`;
DROP TABLE IF EXISTS `AGORA_KI_VISIT`;
DROP TABLE IF EXISTS `AGORA_ARTICLE`;
DROP TABLE IF EXISTS `AGORA_KI`;
DROP TABLE IF EXISTS `AGORA_USER`;
DROP TABLE IF EXISTS `AGORA_BLOB`;
