-- Agora — MVP schema (rollback). Drops every Agora table.
DROP TABLE IF EXISTS `AGORA_NODE_EDGE`;
DROP TABLE IF EXISTS `AGORA_NODE_DYNAMIC`;
DROP TABLE IF EXISTS `AGORA_ARTICLE`;
DROP TABLE IF EXISTS `AGORA_NODE`;
DROP TABLE IF EXISTS `AGORA_USER`;
DROP TABLE IF EXISTS `AGORA_BLOB`;
