(ns landing.routes
  "Defines the routes - all url internals and externals that are potential linked with the website itself.")

(def links
  (->>
    [{:url "/"
      :alt "Home link"
      :text :home
      :link-id :home}
     {:link-id :who-are-we
      :text :who-are-we
      :url "/articles/who-are-we"}
     {:link-id :projets
      :text :projets
      :url "/articles/projets"}
     {:link-id :hephaistox
      :text :hephaistox
      :url "/articles/hephaistox"}
     {:link-id :rivalis
      :text :rivalis
      :url "/articles/rivalis"}
     {:link-id :legal-notice
      :text :legal-notice
      :url "/articles/legal-notice"}
     {:url "/articles/contacts"
      :text :contacts
      :link-id :contacts}
     {:url "/articles/about-site"
      :text :about-this-website
      :link-id :about-this-website}
     {:url "/articles/privacy"
      :text :privacy
      :link-id :privacy}
     {:url "/articles/disclaimer"
      :text :disclaimer
      :link-id :disclaimer}
     {:url "/articles/contact-validated"
      :text :contact-validated
      :link-id :contact-validated}
     {:url "/articles/projets"
      :text :projets
      :link-id :projets}
     {:url "/all-kind-of-checks"
      :text :admin
      :link-id :admin}
     {:url "/articles/advanced-solution-for-industries"
      :text :advanced-industry
      :link-id :advanced-industry}
     {:url "/articles/hephaistox"
      :text :hephaistox
      :link-id :hephaistox}
     {:url "https://github.com/hephaistox"
      :text :github
      :link-id :github}
     {:url "https://www.facebook.com/profile.php?id=61586135248424"
      :text :fb
      :link-id :fb}
     ;; hephaistox.fr
     {:url "mailto:postmaster@hephaistox.fr"
      :link-id :mail-postmaster-hephaistox-fr}
     {:url "mailto:management@hephaistox.fr"
      :link-id :mail-management-hephaistox-fr}
     {:url "mailto:abuse@hephaistox.fr"
      :link-id :mail-abuse-hephaistox-fr}
     {:url "mailto:anthony@hephaistox.fr"
      :link-id :mail-anthony-hephaistox-fr}
     {:url "mailto:info@hephaistox.fr"
      :link-id :mail-info-hephaistox-fr}
     ;; hephaistox.com
     {:url "mailto:postmaster@hephaistox.com"
      :link-id :mail-postmaster-hephaistox.com}
     {:url "mailto:management@hephaistox.com"
      :link-id :mail-management-hephaistox.com}
     {:url "mailto:abuse@hephaistox.com"
      :link-id :mail-abuse-hephaistox.com}
     {:url "mailto:anthony@hephaistox.com"
      :link-id :mail-anthony-hephaistox-com}
     {:url "mailto:info@hephaistox.com"
      :link-id :mail-info-hephaistox-com}
     ;; Mati
     {:url "mailto:mati@hephaistox.fr"
      :link-id :mail-mati-hephaistox-fr}
     {:url "mailto:mati@hephaistox.com"
      :link-id :mail-mati-hephaistox-com}
     ;; A faire
     {:url "mailto:info@hephaistox.fr"
      :skip-test? true
      :text :info-mail
      :link-id :info-mail}
     {:url "https://www.youtube.com/@HephaistoxSC"
      :link-id :youtube}
     {:url "https://www.linkedin.com/in/mateuszmazurczak/"
      :skip-test? true
      :link-id :linkedin-mati}
     {:url "https://www.linkedin.com/in/anthony-caumond-a365b15/"
      :skip-test? true
      :link-id :linkedin-anthony}
     {:url "https://www.linkedin.com/company/hephaistox"
      :skip-test? true
      :link-id :linkedin}
     {:url "https://hephaistox.fr"
      :link-id :production-fr}]
    (mapv (fn [link] [(:link-id link) link]))
    (into {})))

